<?php

defined('_JEXEC') or die('Direct Access to this location is not allowed.');
echo $this->pane->startPane('content-pane');
echo $this->pane->startPanel(JText::_('JGA_MAIMAN_TAB_IMAGES').$this->information['images'], 'cpanel-panel-joom-maintenance-db-images');
echo $this->loadTemplate('dbimages');
echo $this->pane->endPanel();
echo $this->pane->startPanel(JText::_('JGA_MAIMAN_TAB_CATEGORIES').$this->information['categories'], 'cpanel-panel-joom-maintenance-db-categories');
echo $this->loadTemplate('categories');
echo $this->pane->endPanel();
echo $this->pane->startPanel(JText::_('JGA_MAIMAN_TAB_ORPHANS').$this->information['orphans'], 'cpanel-panel-joom-maintenance-file-images');
echo $this->loadTemplate('orphans');
echo $this->pane->endPanel();
echo $this->pane->startPanel(JText::_('JGA_MAIMAN_TAB_ORPHANED_FOLDERS').$this->information['folders'], 'cpanel-panel-joom-maintenance-file-folders');
echo $this->loadTemplate('folders');
echo $this->pane->endPanel();
echo $this->pane->startPanel(JText::_('JGA_MAIMAN_VOTES_MANAGER'), 'cpanel-panel-joom-maintenance-votes');
echo $this->loadTemplate('votes');
echo $this->pane->endPanel();
echo $this->pane->startPanel(JText::_('JGA_MAIMAN_TAB_NAMETAGS'), 'cpanel-panel-joom-maintenance-nametags');
echo $this->loadTemplate('nametags');
echo $this->pane->endPanel();
echo $this->pane->startPanel(JText::_('JGA_COMMAN_COMMENTS_MANAGER'), 'cpanel-panel-joom-maintenance-comments');
echo $this->loadTemplate('comments');
echo $this->pane->endPanel();
echo $this->pane->startPanel(JText::_('JGA_MAIMAN_TAB_DATABASE'), 'cpanel-panel-joom-maintenance-database');
echo $this->loadTemplate('database');
echo $this->pane->endPanel();
echo $this->pane->endPane();
JHTML::_('joomgallery.credits');
